In [10]:
# import dependencies
# Initial imports.
import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from collections import Counter

In [15]:
# Loading data
file_path = Path('../encoded_data.csv')
df = pd.read_csv(file_path)
df

,ID,stint,teamID,lgID,W,L,G,GS,CG,SHO,...,GF,R,SH,SF,GIDP,weight,height,bats,throws,salary
0,2010aardsda01,1,24,0,0,6,53,0,0,0,...,43,19,7.0,1.0,5.0,215.0,75.0,2,1,2750000.0
1,2010accarje01,1,29,0,0,1,5,0,0,0,...,2,6,0.0,0.0,2.0,195.0,72.0,2,1,1080000.0
2,2010aceveal01,1,18,0,3,0,10,0,0,0,...,2,5,0.0,0.0,0.0,205.0,74.0,2,1,435650.0
3,2010adamsmi03,1,23,1,4,1,70,0,0,0,...,3,14,0.0,0.0,2.0,210.0,77.0,2,1,1000000.0
4,2010affelje01,1,25,1,4,3,53,0,0,0,...,14,25,7.0,1.0,4.0,225.0,76.0,1,0,4000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3094,2016youngch03,1,12,0,3,9,34,13,0,0,...,7,63,0.0,4.0,3.0,255.0,82.0,2,1,4250000.0
3095,2016zieglbr01,1,0,1,2,3,36,0,0,0,...,30,13,1.0,1.0,10.0,220.0,76.0,2,1,5500000.0
3096,2016zieglbr01,2,3,0,2,4,33,0,0,0,...,12,8,1.0,0.0,6.0,220.0,76.0,2,1,5500000.0
3097,2016zimmejo02,1,9,0,9,7,19,18,0,0,...,1,63,1.0,5.0,8.0,225.0,74.0,2,1,18000000.0
3098,2016zychto01,1,24,0,1,0,12,0,0,0,...,3,6,0.0,1.0,1.0,190.0,75.0,2,1,511000.0

In [16]:
# Create our features
x_cols=[i for i in df.columns if i not in ('salary','ID')]
X = df[x_cols]


# Create our target
y = df['salary'].ravel()

In [17]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [18]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [19]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

In [20]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [21]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array([  512500.,  7000000.,   515500.,   875000.,  1500000.,   800000.,
        9000000.,  1075000., 15000000.,  1000000.,   500000.,  8500000.,
         517500.,  3250000., 12000000.,  1760000.,   414000.,  1500000.,
        4500000.,  7400000.,   426500.,   405000.,   515000.,  4600000.,
        4000000.,   518000.,  2000000.,  2450000.,  8000000.,   480000.,
        5875000.,   517500., 17000000.,   520000.,   546000.,  2850000.,
        8000000.,  7750000.,  2250000., 13000000.,   750000.,   508000.,
        3950000.,   480000.,  1000000.,   850000., 10000000.,  1200000.,
         508500.,   520700.,  3666667.,   800000.,   519000.,  2000000.,
        3000000.,  7000000.,   406500., 10000000.,  1000000.,   512500.,
         490000.,  1400000.,   490000.,  1250000.,  4500000.,  1350000.,
        4500000.,  6000000.,  1300000.,  5000000., 10000000.,   515000.,
         495000.,   510000.,   750000.,  5000000.,   427500.,  3500000.,
        4000000.,   504500.,  1000000.,  3950000.,  5000000.,  2000000.,
       11000058.,   490500.,  1500000.,  1250000.,   480000., 22000000.,
         507500.,  1000000.,  5000000.,  1000000.,  7300000.,  9000000.,
         527500.,  1475000.,   513900.,  3000000.,  9187500.,   425000.,
         500000.,  5875000.,   484000.,   502550.,   510000.,  1200000.,
        1500000.,   900000.,  4837500., 10000000.,  1000000., 11625000.,
         950000.,   557000.,   480000., 18000000.,   520000.,   480000.,
        6500000.,   400000.,  9000000.,   850000.,   413500., 10000000.,
        1000000.,   480000.,   445000.,  1000000.,  3466666., 17000000.,
        3655333.,  1000000.,   490840.,  1450000.,  5500000.,  1750000.,
        2500000.,   550000.,   750000.,  2000000.,  4250000.,  5500000.,
        1500000.,   409500.,   509500.,   510000.,   514000.,  9000000.,
         900000.,  9000000.,  1000000., 13500000.,  1850000.,  1795000.,
         700000., 13500000.,  1500000.,  1000000.,  2000000.,  5000000.,
        5000000.,   950000.,  1900000.,   500000.,   522000.,  9000000.,
         516000.,  8000000.,   875000.,   502000.,   512500., 13000000.,
         508000.,  1300000.,   507500.,   510000.,   850000.,   440000.,
        9000000.,  5000000.,  2000000., 10500000.,   440000., 10250000.,
         400000.,  8000000.,   520000., 12850000., 25000000.,  3000000.,
         530000.,  6000000.,   414000.,   500500.,  1400000.,  3000000.,
        2500000.,  4000000.,   520000.,   527500., 14200000.,   400000.,
         530000.,   406000.,  2000000.,   507500.,  1500000.,   535000.,
       18000000.,   415000.,   900000.,  2000000.,  3000000., 10133333.,
        9850000.,  1500000.,   519000.,  3000000.,   495000.,  4500000.,
        1250000.,  3625000.,   513000.,  1750000., 11000000.,  2750000.,
        4000000.,  2950000., 12187500.,   431500.,  3000000.,   490840.,
         502200.,  4000000., 25000000.,  3625000.,   515400.,  6250000.,
        8000000.,   509500.,   480000.,  3500000.,   509500.,  7500000.,
        4500000.,  5000000.,  1250000.,   522500.,   416500.,   450000.,
         515000.,  2000000.,   500000.,  3825000., 18875000.,   650000.,
         513100.,  3000000.,   912500., 10000000.,  3000000.,  3000000.,
        5600000., 24285714.,   700000.,   480000.,   488000.,  5000000.,
         414000.,   512500., 14000000.,   512500.,  5000000.,  6500000.,
        1330000.,   441500.,   490000.,  6300000.,  7250000.,  4000000.,
        7000000.,  3300000.,   509300.,   400000.,   499000.,  4837500.,
        3466666.,  9500000., 10000000., 22000000.,  1000000.,  6000000.,
        5000000.,   490840.,   482000.,   512500.,   420000.,  1500000.,
         527000.,  4250000.,   400000.,  3000000.,   502500., 15800000.,
        1080000.,  1075000.,  1820000.,  9000000.,  4000000.,   509500.,
        1000000.,  7500000.,   441500., 13500000.,   523000.,  2000000.,
         415000.,   400000.,  9000000.,   400000.,  7000000.,   424000.,
        1350000.,   516000.,  1600000.,  5500000.,  4600000.,  1375000.,
        5000000.,   507500.,  3650000.,  2000000.,  1500000., 12000000.,
        7500000.,   485900.,  4850000.,   414700.,   517500., 12500000.,
         406000.,   503100.,  6750000.,  8000000., 12500000.,   489100.,
         750000.,   411000.,   480000.,   480000.,  4837500.,   518000.,
         850000., 13500000.,   507500.,   410000.,   480000.,  5000000.,
        1700000.,   512000., 10000000.,   480000.,  4275000., 25000000.,
         935000.,   509500.,  3000000.,  1000000.,  6000000.,  3000000.,
         900000., 13500000.,   470000.,  2650000.,   419000., 12166666.,
       12750000.,   550000.,   505000.,  2300000.,   509500.,   725000.,
         510000.,   482500., 13000000.,  1000000.,  2000000.,  1250000.,
        1000000.,  3000000.,   414000.,  2300000.,  3000000.,  5000000.,
         515800.,   490500.,   900000.,   416000.,  1000000.,   480000.,
        2237500.,   557000.,   800000.,   488500.,  2000000., 12125000.,
        5000000.,   517100.,   539500.,   507500.,   416000.,   506100.,
        5000000.,   401500.,   504500.,  1500000.,  2500000.,  1625000.,
         500000., 16445535.,   512500.,   502200.,  5000000.,   513000.,
        5000000., 25000000.,  9200000.,   700000.,  1250000.,  3000000.,
        4500000.,   408300.,  5500000.,  3700000.,   412500.,   484000.,
        1500000., 11000000.,  7250000.,   419000.,  7000000.,   414000.,
        5000000.,  5000000.,  3800000.,  4275000.,   427000.,  3250000.,
        1500000.,  4700000.,  4000000.,   494500.,  1050000.,   417500.,
       16500000.,  2000000.,  3200000.,   519700.,  4000000.,  4000000.,
         504000.,   507500.,   480000.,  1500000.,   480000.,  3000000.,
         900000.,   505500.,  2640000.,  5000000.,   480000.,  5500000.,
        9000000.,  4000000.,   440000.,   514000.,  1290000., 13000000.,
        7150000.,  5500000.,   900000.,   419000.,   750000.,   508500.,
        1250000.,   500000.,  1500000.,   507500.,  5000000.,  5500000.,
         480000.,  1500000.,  2800000.,   498750.,   414000.,   512375.,
         414000.,  1300000.,  3500000.,  4250000.,  2500000.,   725000.,
         406210.,  7000000.,   505500.,  2000000.,  2400000.,   504500.,
        8200000.,   507500.,   500000.,  1075000.,   515000.,  8000000.,
         850000.,  9000000.,   510000.,  1675000., 15000000.,   509500.,
        5500000.,  1400000.,   491500.,  5500000.,  9000000.,   508000.,
        1075000.,  1250000.,   481000.,  3000000.,   512500.,  8000000.,
         507000.,  4500000.,   525270.,  1500000.,  4200000.,  5500000.,
       22142857.,  3000000.,  4000000.,  7000000.,  2000000.,   517500.,
        2000000.,  1400000.,  2200000.,   510000.,  3000000.,   800000.,
        4000000.,  1100000.,   414000.,   522500.,  4500000.,   492500.,
        1500000.,   520000.,  1700000.,  3000000.,  7500000.,  3000000.,
       13000000.,  7400000.,   519000.,   519550.,   414000.,   415000.,
        5000000., 10700000.,  4275000.,  5500000.,  1000000.,   486000.,
         523000.,   502500.,   516100.,   820000.,  4000000.,  4000000.,
         419000.,  1000000., 13500000.,  5500000.,   510000.,   505000.,
        1500000., 12000000.,  3900000.,   486000.,   509500.,   419000.,
       10250000.,   416000.,  1000000.,   407800.,  7000000.,   900000.,
       24857000.,  1750000.,   497400.,   480000., 11000000.,  5750000.,
        9000000.,  5000000.,  1000000.,   525500.,  5000000., 10000000.,
         507500.,   416000.,   480000.,  3200000.,   520000.,  2000000.,
        3000000.,  3500000.,   524100.,   405000.,   925000.,   416500.,
         480000.,  4000000.,   416500.,  1400000.,  1550000.,   517500.,
       13000000.,  1500000.,  5000000.,  5000000.,  6750000.,   519000.,
        3350000., 22000000.,   950000.,  8000000.,   513000.,   414000.,
        1800000.,   517500.,  1000000.,  7000000.,  3000000.,  1500000.,
        1415000.,   484000., 16000000.,  4500000.,   483000., 12000000.,
         497000., 13000000.,  8525000.,  9000000.,  6000000.,  8000000.,
         508500.,  1700000.,  7000000.,  5000000.,  7675000.,  5000000.,
         507500.,   419000.,   502000.,  1050000.,   411000.,  1500000.,
        3500000.,  6250000.,  4000000.,   419000.,  9000000.,  9400000.,
        4250000., 11765724.,  1000000.,  6500000.,   415000.,   533400.,
        4000000.,  5500000.,  8525000., 13500000.,   507500.,  5500000.,
         750000.,   521400.,   402000.,  1200000.,   950000.,   900000.,
        1250000.,   517100.,   600000.,   515000.,  1250000.,  7000000.,
         950000.,  2000000.,  5500000.,   501900.,  3200000.,   517300.,
        4250000., 13000000.,   950000.,   750000.,   510000.,  3000000.,
         725000.,  1500000.,   400000.,  5000000.,  2445000.,  7000000.,
         900000.,  1290000.,   900000.,   400000.,   498900.,  6000000.,
         695000.,   505000., 11000000.,  4275000., 16000000.,  5000000.,
        5500000.,  8000000.,  2000000.,   485000.,  2000000.,   509500.,
        1075000.,  6100000.,   509500.,   510000.,   529000.,  3000000.,
         546000.,   414000.,  2225000.,  1055000.,   520000., 12000000.,
         510800., 10000000.,  3500000.,  9000000.,   505000.,  4000000.,
       13500000.,  5500000.,  4000000.,   512500.,   500500.,   484000.,
         488925.,  1000000.,  1750000.,  1200000.,  4000000.,  4500000.,
        1500000.,  3250000.,   900000.,  3000000.,  4000000.,  1250000.,
        1400000.])

In [22]:
# balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, predictions)

C:\Users\alyss\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1987: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

0.01150358262427228

In [23]:
# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)
acc_score

0.016774193548387096

In [24]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.00602158, 0.04690225, 0.01349107, 0.03076697, 0.03057612,
       0.04194446, 0.0177727 , 0.00662662, 0.0046511 , 0.01662592,
       0.0439115 , 0.04224166, 0.0392944 , 0.03758027, 0.04579844,
       0.04574746, 0.04918551, 0.04861605, 0.02843406, 0.03337596,
       0.03120219, 0.01362568, 0.04386372, 0.03269578, 0.03950936,
       0.02994834, 0.02854083, 0.03742029, 0.04746413, 0.0405229 ,
       0.01453803, 0.01110468])

In [25]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.04918550729331832, 'BAOpp'),
 (0.0486160472546323, 'ERA'),
 (0.047464125558374586, 'weight'),
 (0.04690224814195206, 'teamID'),
 (0.04579843754661403, 'BB'),
 (0.045747456782583434, 'SO'),
 (0.04391149997272195, 'IPouts'),
 (0.043863717646994455, 'BFP'),
 (0.04224165879422784, 'H'),
 (0.041944464151434144, 'G'),
 (0.0405229018469237, 'height'),
 (0.03950935577130806, 'R'),
 (0.03929440407774342, 'ER'),
 (0.03758027042918364, 'HR'),
 (0.037420290355144624, 'GIDP'),
 (0.03337595776005236, 'WP'),
 (0.03269578351309893, 'GF'),
 (0.031202190668776712, 'HBP'),
 (0.03076696604302849, 'W'),
 (0.0305761179225366, 'L'),
 (0.029948341060881803, 'SH'),
 (0.028540830170696887, 'SF'),
 (0.028434056554171697, 'IBB'),
 (0.0177726952551777, 'GS'),
 (0.01662592429618595, 'SV'),
 (0.01453802730000197, 'bats'),
 (0.013625681822139931, 'BK'),
 (0.013491065975362265, 'lgID'),
 (0.011104678555766568, 'throws'),
 (0.006626618892987021, 'CG'),
 (0.00602158122097796, 'stint'),
 (0.004651097365000634, 'SHO')]